apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.team_name}}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
