apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.team_name}}
  description: ${{values.description}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}