name: ci-py-docker
on: 
  push:
    branches:
      - develop
      - master
      - release
jobs:
  ci:
    uses: Toyota-Motor-North-America/chofer-actions/.github/workflows/ci-py-docker.yml@v1
    secrets: inherit
  cd:
    uses: Toyota-Motor-North-America/chofer-actions/.github/workflows/cd-sgm-train.yml@feature/tdspds-mlops
    needs: ci
    secrets: inherit
    with:
      image-tag: ${{ needs.ci.outputs.docker-tag }}
    
